apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-lab4
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end2
          image: sergueidb/lab4-3:master # sergueidb/rsoi-lab4:master #  public.ecr.aws/nginx/nginx:1.21 #
          ports:
            - containerPort: 8080