kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi